# Форматы данных (1)

Материалы:
* Макрушин С.В. "Лекция 4: Форматы данных"
* https://docs.python.org/3/library/json.html
* https://docs.python.org/3/library/pickle.html
* https://www.crummy.com/software/BeautifulSoup/bs4/doc.ru/bs4ru.html
* Уэс Маккини. Python и анализ данных

## Лабораторная работа №3

### JSON

In [79]:
import json
import pickle

with open("addres-book.json", "r", encoding="utf-8") as f:
    data = json.load(f)

1.1 Считайте файл `contributors_sample.json`. Воспользовавшись модулем `json`, преобразуйте содержимое файла в соответствующие объекты python. Выведите на экран информацию о первых 3 пользователях.

In [80]:
class User:

    def __init__(self, username, name, sex, address, mail, jobs, id):
        self.username = username
        self.name = name
        self.sex = sex
        self.address = address
        self.mail = mail
        self.jobs = jobs
        self.id = id

    def __str__(self) -> str:
        jobs_str = ", ".join(self.jobs)
        return f"\nId: {self.id}\nUsername: {self.username}\nName: {self.name}\nSex: {self.sex}\naddress: {self.address}\nmail: {self.mail}\njobs: {jobs_str}\n\n#########################"


with open("contributors_sample.json", "r", encoding="utf8") as f:
    data = json.load(f)

user_l = []
for i in data:
    user_l.append(User(**i))

for usr in user_l[:3]:
    print(usr)

Id: 35193
Username: uhebert
Name: Lindsey Nguyen
Sex: F
address: 01261 Cameron Spring
Taylorfurt, AK 97791
mail: jsalazar@gmail.com
jobs: Energy engineer, Engineer, site, Environmental health practitioner, Biomedical scientist, Jewellery designer

#########################

Id: 91970
Username: vickitaylor
Name: Cheryl Lewis
Sex: F
address: 66992 Welch Brooks
Marshallshire, ID 56004
mail: bhudson@gmail.com
jobs: Music therapist, Volunteer coordinator, Designer, interior/spatial

#########################

Id: 1848091
Username: sheilaadams
Name: Julia Allen
Sex: F
address: Unit 1632 Box 2971
DPO AE 23297
mail: darren44@yahoo.com
jobs: Management consultant, Engineer, structural, Lecturer, higher education, Theatre manager, Designer, textile

#########################

1.2 Выведите уникальные почтовые домены, содержащиеся в почтовых адресах людей

In [81]:
l = []
for i in data:
    dom = i["mail"].split("@")[1]
    if dom not in l:
        l.append(i["mail"].split("@")[1])

print(l)

['gmail.com', 'yahoo.com', 'hotmail.com']

1.3 Напишите функцию, которая по `username` ищет человека и выводит информацию о нем. Если пользователь с заданным `username` отсутствует, возбудите исключение `ValueError`

In [82]:
# введём настоящий юзернейм
def find_username(username):
    try:
        for item in data:
            if username == item['username']:
                print(item)
                return

        raise ValueError
    except ValueError:
        print('Error: user not found')

find_username(input())

uhebert
{'username': 'uhebert', 'name': 'Lindsey Nguyen', 'sex': 'F', 'address': '01261 Cameron Spring\nTaylorfurt, AK 97791', 'mail': 'jsalazar@gmail.com', 'jobs': ['Energy engineer', 'Engineer, site', 'Environmental health practitioner', 'Biomedical scientist', 'Jewellery designer'], 'id': 35193}

In [39]:
# выведем ошибку
def find_username(username):
    try:
        for item in data:
            if username == item['username']:
                print(item)
                return

        raise ValueError
    except ValueError:
        print('Error: user not found')

find_username(input())

daria147
Error: user not found

1.4 Посчитайте, сколько мужчин и женщин присутсвует в этом наборе данных.

In [83]:
def male_female():
    m, f = 0, 0
    for i in data:
        if i["sex"] == "M":
            m += 1
        else:
            f += 1
    return f"Мужчин: {m}, женщин: {f}"

male_female()

'Мужчин: 2064, женщин: 2136'

1.5 Создайте `pd.DataFrame` `contributors`, имеющий столбцы `id`, `username` и `sex`.

In [42]:
import pandas as pd
    
contributors = pd.read_json("contributors_sample.json").drop(["name", "address", "mail", "jobs"], axis=1)
col = contributors.pop("id")
contributors.insert(0, col.name, col)
print(contributors)

           id       username sex
0       35193        uhebert   F
1       91970    vickitaylor   F
2     1848091    sheilaadams   F
3       50969       nicole82   F
4      676820         jean67   M
...       ...            ...  ..
4195   423555  stevenspencer   F
4196    35251      rwilliams   M
4197   135887      lmartinez   F
4198   212714     brendahill   M
4199   344321       mistyray   F

[4200 rows x 3 columns]

1.6 Загрузите данные из файла `recipes_sample.csv` (__ЛР2__) в таблицу `recipes`. Объедините `recipes` с таблицей `contributors` с сохранением строк в том случае, если информация о человеке отсутствует в JSON-файле. Для скольких человек информация отсутствует?

In [43]:
recipes = pd.read_csv("recipes_sample.csv", sep=",")
recipes = recipes.merge(contributors, left_on="contributor_id", right_on="id", how="left")
recipes = recipes[pd.isna(recipes["id_y"])] # если информация отсутствует
print(len(recipes["contributor_id"].unique()))

4204

### pickle

2.1 На основе файла `contributors_sample.json` создайте словарь следующего вида: 
```
{
    должность: [список username людей, занимавших эту должность]
}
```

In [50]:
with open("contributors_sample.json", "r", encoding="utf8") as f:
    data = json.load(f)

d = {}
for i in data:
    for job in i["jobs"]:
        if job not in d:
            d[job] = []
        d[job].append(i["username"])


# print({k: d[k] for k in list(d)})
#выведет весь словарь, для лучшей читаемости выведу лишь часть, чтобы вам не пришлось долго скроллить на гитхабе :) 

print({k: d_pickle[k] for k in list(d_pickle)[:3]})

{'Energy engineer': ['uhebert', 'annmoore', 'garysilva', 'martinezashley', 'sextonsheila', 'pjames', 'smithjonathan', 'wardjames', 'cwheeler', 'ucarlson', 'robert71', 'johnsontheresa', 'amanda41', 'stacey47', 'timothynelson', 'timothynelson', 'rogersmichael', 'melissa94', 'wmcdaniel', 'charles74', 'smithjennifer', 'clintonjones'], 'Engineer, site': ['uhebert', 'nancy12', 'andrea03', 'catherineross', 'wesley32', 'natalieross', 'rossdoris', 'christophersmith', 'dbooker', 'ericarobertson', 'trantricia', 'tpugh', 'jasonvelez', 'samantha36', 'brandidaniels', 'tenglish', 'reyesbrett', 'austin18', 'vjohnson', 'zmejia', 'daniel04', 'cynthia20', 'morgan15', 'avaldez', 'jessica92', 'laurieholloway', 'baileyvictoria'], 'Environmental health practitioner': ['uhebert', 'jonathanchristian', 'xjohnson', 'dsmith', 'james01', 'nancytaylor', 'ztaylor', 'andrewwoods', 'susan54', 'fmaldonado', 'james74', 'bakerjacob', 'stephanie81', 'whitejoseph', 'qolson', 'hknox', 'gonzalesdaniel', 'tranronald', 'jessegreen', 'stephanie69', 'ellisdennis', 'melaniejohnson', 'bradleyalexander', 'chadandrews', 'thomas33', 'john93', 'tanderson', 'dward', 'kathleenbarnett']}

2.2 Сохраните результаты в файл `job_people.pickle` и в файл `job_people.json` с использованием форматов pickle и JSON соответственно. Сравните объемы получившихся файлов. При сохранении в JSON укажите аргумент `indent`.

In [84]:
with open("job_people.pickle", "wb") as f:
    pickle.dump(d, f)

with open("job_people.json", "w") as f:
    json.dump(d, f, indent=1)
    
# объёмы
import os
print("pickle :", os.path.getsize("job_people.pickle"))
print("json   :", os.path.getsize("job_people.json"))

pickle : 132272
json   : 285159

2.3 Считайте файл `job_people.pickle` и продемонстрируйте, что данные считались корректно.

In [51]:
with open("job_people.pickle", "rb") as f:
    d_pickle = pickle.load(f)

print({k: d_pickle[k] for k in list(d_pickle) [:3]}) 

# выводится тот же словарь

{'Energy engineer': ['uhebert', 'annmoore', 'garysilva', 'martinezashley', 'sextonsheila', 'pjames', 'smithjonathan', 'wardjames', 'cwheeler', 'ucarlson', 'robert71', 'johnsontheresa', 'amanda41', 'stacey47', 'timothynelson', 'timothynelson', 'rogersmichael', 'melissa94', 'wmcdaniel', 'charles74', 'smithjennifer', 'clintonjones'], 'Engineer, site': ['uhebert', 'nancy12', 'andrea03', 'catherineross', 'wesley32', 'natalieross', 'rossdoris', 'christophersmith', 'dbooker', 'ericarobertson', 'trantricia', 'tpugh', 'jasonvelez', 'samantha36', 'brandidaniels', 'tenglish', 'reyesbrett', 'austin18', 'vjohnson', 'zmejia', 'daniel04', 'cynthia20', 'morgan15', 'avaldez', 'jessica92', 'laurieholloway', 'baileyvictoria'], 'Environmental health practitioner': ['uhebert', 'jonathanchristian', 'xjohnson', 'dsmith', 'james01', 'nancytaylor', 'ztaylor', 'andrewwoods', 'susan54', 'fmaldonado', 'james74', 'bakerjacob', 'stephanie81', 'whitejoseph', 'qolson', 'hknox', 'gonzalesdaniel', 'tranronald', 'jessegreen', 'stephanie69', 'ellisdennis', 'melaniejohnson', 'bradleyalexander', 'chadandrews', 'thomas33', 'john93', 'tanderson', 'dward', 'kathleenbarnett']}

### XML

3.1 По данным файла `steps_sample.xml` сформируйте словарь с шагами по каждому рецепту вида `{id_рецепта: ["шаг1", "шаг2"]}`. Сохраните этот словарь в файл `steps_sample.json`

In [57]:
from bs4 import BeautifulSoup

with open('steps_sample.xml') as f:
    data = BeautifulSoup(f, features="xml")
    
recipe_book = {}
for recipe in data.find_all('recipe'):
    id = recipe.find('id')
    if id.text not in recipe_book:
        recipe_book[id.text] = []
    for step in recipe.find_all('step'):
        recipe_book[id.text].append(step.text)

with open('steps_sample.json', 'w') as f:
    json.dump(recipe_book, f)

3.2 По данным файла `steps_sample.xml` сформируйте словарь следующего вида: `кол-во_шагов_в_рецепте: [список_id_рецептов]`

In [60]:
step_recipe = {}
for recipe in data_xml.find_all("recipe"):
    step_count = len(recipe.find_all("step"))
    if step_count not in step_recipe:
        step_recipe[step_count] = []
    step_recipe[step_count].append(recipe.find("id").text)

print({k: step_recipe[k] for k in list(step_recipe)[:2]}) # [:2] для лучшей читаемости

{11: ['44123', '302399', '375376', '140610', '374703', '111198', '257111', '432661', '114204', '63069', '165096', '33947', '250024', '330512', '315233', '25259', '331174', '407621', '263019', '112853', '383729', '13709', '336166', '143286', '387284', '290003', '370746', '34833', '11975', '426211', '373582', '88845', '456968', '14149', '507927', '73602', '91981', '175109', '390933', '193208', '83893', '243008', '259789', '303926', '410920', '446605', '32571', '74419', '308056', '78497', '111963', '361181', '302640', '356655', '53743', '57771', '420689', '74520', '50851', '176277', '266814', '27897', '189207', '138771', '279797', '177831', '32515', '256842', '95295', '383349', '109791', '332641', '116993', '173126', '187872', '177681', '249006', '314834', '283033', '117084', '49202', '284916', '247657', '313162', '424727', '227557', '431305', '263038', '439979', '443041', '241042', '258779', '66965', '200503', '109597', '503121', '290595', '401175', '169146', '282228', '316435', '248582', '504422', '196814', '153793', '36709', '158200', '410513', '191457', '82108', '157276', '28648', '176753', '8565', '300625', '45429', '65897', '102457', '476511', '7036', '449701', '405140', '42526', '360', '224714', '421620', '209347', '110941', '390645', '429589', '295611', '60877', '351891', '137873', '83572', '138305', '204963', '351642', '184280', '52100', '323574', '17782', '208078', '248015', '451177', '60476', '104632', '165769', '434085', '445456', '182234', '159843', '137263', '95284', '137031', '431954', '59257', '1075', '131027', '48378', '422595', '363299', '262605', '320218', '445628', '387882', '211279', '136589', '417786', '407145', '98988', '99034', '262188', '56366', '444125', '8765', '464745', '382880', '214206', '364032', '332582', '310605', '332822', '122527', '515641', '484413', '10869', '189860', '495331', '229779', '201338', '359664', '289766', '179690', '57408', '16407', '206824', '143396', '52089', '205831', '313058', '452758', '231928', '312998', '54945', '29618', '323013', '372807', '217210', '82678', '151210', '287887', '139971', '394247', '414491', '99649', '433349', '352200', '122070', '117238', '98530', '371606', '386601', '211473', '337971', '88060', '71804', '191965', '114023', '134026', '136364', '69389', '272841', '171041', '134263', '87226', '300644', '53757', '332540', '378226', '19664', '71975', '137727', '472794', '295769', '75835', '53445', '253666', '78195', '514138', '62530', '31730', '458694', '481770', '67252', '235218', '40045', '133992', '101752', '113176', '103408', '126610', '311511', '402757', '75066', '195954', '137902', '466342', '16209', '336795', '456864', '476209', '329752', '265167', '45455', '128604', '429328', '73743', '288266', '170339', '194571', '140498', '409348', '134260', '389964', '17602', '40888', '273470', '183829', '65802', '158312', '236879', '383588', '98007', '285076', '193649', '319720', '101036', '132678', '314281', '62166', '380695', '265953', '216859', '335134', '73335', '357845', '359086', '521815', '494677', '54383', '482954', '8444', '245634', '82339', '70274', '417510', '336955', '49511', '450542', '389504', '116299', '31049', '226959', '432667', '351403', '77152', '243335', '79461', '25396', '461136', '12548', '124256', '117192', '99986', '94410', '63564', '399381', '99073', '20482', '26378', '294898', '319962', '240', '19708', '356639', '449638', '316237', '211581', '288142', '497379', '336724', '238679', '391921', '93808', '169662', '138865', '425992', '315293', '229687', '334290', '335434', '221083', '68452', '465971', '48782', '253341', '467385', '161069', '315376', '330114', '125533', '66698', '95609', '279702', '203500', '277319', '74367', '136265', '23689', '296109', '148407', '141419', '283527', '59000', '467705', '357689', '352781', '152573', '364177', '159942', '90444', '239895', '93989', '168981', '139762', '205348', '91775', '161909', '70625', '19783', '199197', '483179', '127187', '118337', '345304', '404889', '4380', '259088', '286105', '81769', '506630', '395749', '337682', '283191', '107955', '437819', '104002', '326620', '410350', '366106', '196802', '392761', '373383', '144258', '369016', '455881', '127017', '51555', '449495', '401462', '443975', '65681', '219237', '385797', '27099', '457353', '104074', '61037', '122139', '416088', '484376', '118256', '235758', '42900', '14835', '38742', '47264', '413633', '467154', '380719', '180837', '54593', '62794', '291683', '447364', '253676', '115221', '127714', '85461', '13800', '58387', '197962', '195298', '180812', '8473', '77452', '154386', '30398', '140352', '312734', '241905', '64005', '30459', '125633', '119560', '292876', '105146', '147357', '384801', '484788', '95798', '460245', '31197', '36950', '204491', '266513', '326977', '266236', '278836', '104492', '256460', '154298', '146874', '142220', '64701', '167854', '191359', '304741', '280949', '230435', '24515', '475468', '251827', '123934', '257308', '197609', '317022', '81065', '64913', '360467', '58587', '329426', '191818', '388695', '263802', '341593', '424577', '95464', '63443', '200378', '98691', '401411', '13565', '325662', '11639', '413552', '340142', '432871', '221773', '194103', '41524', '109068', '439037', '228850', '448503', '392864', '251550', '453396', '133124', '25046', '136815', '12638', '381211', '178218', '117641', '189312', '289466', '59256', '414568', '152237', '98985', '328747', '85874', '198754', '44069', '276136', '88306', '12313', '114199', '308706', '327793', '635', '225660', '157901', '128964', '482034', '220329', '198071', '45709', '41681', '179663', '74703', '164245', '93048', '14637', '83885', '204958', '186466', '465453', '95569', '51801', '265632', '393637', '353660', '326058', '418258', '291158', '513160', '247728', '71154', '439316', '399482', '118383', '356320', '383670', '20176', '176482', '272854', '158353', '360031', '265578', '19070', '70263', '245850', '269030', '240127', '301905', '193972', '402061', '222739', '98061', '465388', '195998', '21197', '68566', '269340', '90804', '83484', '110848', '173635', '195881', '241196', '350933', '36806', '15250', '158322', '106677', '295675', '242821', '229455', '340197', '87801', '266070', '128167', '64704', '78216', '282901', '233781', '94555', '285641', '18201', '192825', '161798', '115713', '397621', '243947', '130768', '113657', '249646', '403928', '163713', '198730', '41295', '502882', '155815', '22240', '252028', '71358', '152368', '224084', '149818', '515670', '587', '244522', '129710', '343486', '65493', '279465', '90884', '86629', '387606', '312689', '298882', '165473', '446432', '460434', '171343', '54345', '30228', '439090', '262327', '243374', '476676', '292204', '238730', '237228', '15905', '85523', '156107', '207998', '278206', '259594', '102041', '363441', '146177', '423800', '80399', '154833', '257177', '134829', '425085', '98330', '209563', '219281', '325414', '325869', '102321', '57995', '68585', '424553', '84919', '57810', '393801', '278868', '65276', '86521', '212683', '68579', '114076', '296315', '70932', '274186', '40093', '201442', '406784', '71244', '186887', '177713', '364099', '170037', '462565', '503830', '327292', '226778', '220655', '68503', '30099', '217552', '137968', '136927', '148503', '99697', '307564', '364326', '70538', '248620', '318257', '109797', '450425', '174666', '180873', '143734', '39375', '372814', '319842', '240671', '56096', '368489', '33191', '177689', '210610', '405675', '95516', '361971', '370000', '122289', '155198', '195666', '64699', '183935', '158356', '461081', '176025', '53879', '187113', '449877', '34063', '85583', '232766', '139904', '48852', '446808', '367834', '84614', '133693', '32059', '482707', '192868', '53272', '47085', '429393', '248717', '423414', '190403', '483225', '469591', '231267', '285113', '294772', '396008', '153610', '95950', '470194', '6848', '239061', '238758', '32771', '509731', '426825', '443215', '132360', '313181', '131922', '58598', '141047', '222659', '207971', '480108', '75242', '358971', '486320', '16227', '79970', '30521', '138282', '210106', '105108', '140969', '61769', '158243', '390087', '52194', '340327', '124810', '197572', '79497', '102151', '506142', '209319', '214400', '58633', '504603', '190277', '419912', '196794', '229942', '484075', '111309', '335471', '254815', '519642', '465392', '230194', '270633', '457203', '473972', '189686', '51799', '17588', '211765', '190872', '472337', '343596', '227921', '186196', '278031', '426903', '147176', '384513', '103583', '387741', '123173', '217915', '369021', '126623', '38617', '482933', '441181', '49543', '110613', '42169', '409064', '106214', '313366', '333907', '324032', '90708', '171769', '256623', '60711', '221838', '495702', '399476', '171728', '218125', '313911', '119804', '194297', '191490', '74512', '382047', '164821', '337879', '76513', '488522', '242990', '34760', '73081', '208451', '235054', '344733', '186780', '102446', '103370', '457620', '318734', '289227', '308893', '246032', '427634', '135924', '21321', '221092', '138680', '4413', '212090', '140579', '125573', '338841', '97905', '62240', '89439', '505610', '251751', '51412', '97572', '298391', '323521', '203686', '104430', '86620', '381018', '327776', '90382', '259198', '358810', '154666', '288003', '142822', '241286', '6913', '226450', '513850', '404918', '394765', '84616', '348505', '61561', '169394', '74890', '24370', '58245', '274121', '56976', '384502', '363341', '227743', '322018', '213436', '12243', '299146', '241714', '200097', '327496', '190185', '146250', '57208', '169175', '149751', '423301', '73911', '82451', '189175', '399380', '256055', '479880', '235909', '333283', '464049', '329809', '79884', '104222', '316695', '455040', '323752', '272941', '295199', '216504', '104098', '418062', '190963', '133987', '294949', '349579', '400015', '17674', '472531', '336083', '359405', '153467', '131542', '139011', '304619', '320613', '364436', '131972', '337418', '290726', '236367', '69738', '12272', '104309', '39895', '220808', '15335', '245773', '265909', '203423', '397659', '4876', '16489', '147986', '135165', '48910', '466325', '324038', '425059', '512678', '230031', '199510', '160323', '291807', '244935', '308473', '355686', '172164', '208622', '403441', '26121', '23422', '250153', '143879', '438160', '329675', '6517', '43987', '92037', '72442', '166701', '25793', '2771', '30536', '264539', '328774', '374647', '159175', '457195', '52021', '338134', '17531', '214318', '227008', '285449', '468435', '315466', '280660', '337084', '115730', '435975', '188211', '287243', '387262', '232873', '448875', '311354', '145769', '85855', '142043', '356814', '398355', '500230', '209406', '223030', '36755', '364203', '108062', '284546', '375440', '54369', '504600', '102850', '272804', '328636', '233808', '76868', '182725', '261460', '109762', '386630', '298195', '163891', '337545', '254361', '327755', '138090', '121214', '304165', '10183', '31199', '147678', '297707', '177680', '125951', '135101', '140095', '412938', '358468', '138606', '39451', '159934', '244618', '306106', '77009', '144082', '308579', '206184', '382373', '483662', '497230', '19970', '465662', '89629', '269711', '518413', '127953', '58511', '410925', '427637', '463758', '12082', '141979', '256578', '205412', '255890', '53361', '377629', '265185', '14217', '319308', '380340', '37170', '231413', '67039', '228677', '92884', '436444', '45707', '363203', '435580', '246521', '93610', '386877', '98446', '176862', '149561', '156930', '157200', '111321', '185909', '88392', '272020', '252909', '255749', '250470', '206956', '25210', '236900', '255415', '170697', '16220', '286738', '125997', '313920', '20492', '63116', '533571', '120391', '140062', '304784', '288393', '52911', '37065', '14464', '237896', '445091', '294715', '418188', '202748', '231644', '50889', '369386', '263677', '1442', '22706', '116009', '115669', '83077', '121865', '206229', '297985', '104453', '112526', '429993', '453965', '253488', '360371', '391592', '315517', '136957', '330881', '82976', '45213', '68833', '249927', '303412', '290922', '68611', '72373', '355213', '140947', '19823', '150971', '59223', '217437', '72706', '266206', '43051', '370711', '59367', '19726', '88670', '123867', '22917', '56940', '223212', '114423', '50504', '12515', '224785', '354850', '332014', '25548', '18993', '427317', '495453', '258891', '286928', '294205', '42667', '148307', '210687', '157010', '25076', '451490', '252216', '124004', '316579', '379274', '74007', '323214', '143049', '412991', '15727', '124713', '56401', '241671', '123262', '463364', '12368', '38377', '498285', '107741', '294045', '87345', '426628', '153827', '170402', '139612', '338946', '106562', '74443', '10727', '145324', '42257', '387352', '113115', '343493', '360136', '39574', '122193', '428481', '177196', '422216', '388328', '380254', '246902', '26455', '483089', '533575', '117467', '239068', '13223', '430912', '8380', '338517', '118957', '345347', '172973', '338887', '172884', '447194', '477668', '399814', '302898', '62908', '216676', '186130', '266969', '327918', '197061', '384385', '240190', '411899', '311712', '331868', '430600', '228787', '392943', '319963', '107464', '75297', '57880', '143514', '34490', '234274', '45048', '466372', '174710', '115543', '61120', '425657', '356210', '90470', '449461', '19742', '63196', '58885', '175611', '161570', '450834', '359163', '236922', '186055', '402725', '43762', '318156', '330652', '290592', '182231', '155945', '381243', '410359', '17398', '456655', '380018', '76305', '327941', '393496', '343409', '276426', '512345', '253499', '219606', '389129', '300638', '197712', '92298', '40178', '310364', '153538', '145623', '386521', '86534', '375841', '284885', '43901', '230521', '327887', '282197', '301665', '62204', '260298', '23627', '161808', '137874', '18691', '110022', '160743', '288686', '306155', '100908', '321751', '203279', '186180', '108311', '173638', '66409', '34316', '127458', '33888', '178492', '19593', '221913', '188615', '34372', '91817', '536212', '346491', '107029', '336205', '330891', '144789', '113428', '422858', '189781', '410916', '26941', '241903', '70758', '417170', '246783', '21999', '123132', '191064', '83890', '454850', '335763', '30602', '52944', '239800', '322829', '171466', '177786', '121412', '35619', '133407', '82276', '333110', '74951', '503754', '81102', '145441', '362505', '167488', '518980', '415308', '172810', '289075', '182403', '28818', '180161', '39137', '413952', '463832', '300503', '16591', '488873', '71036', '71626', '416438', '113424', '202352', '149534', '351214', '406060', '421930', '467750', '426148', '355732', '271659', '438227', '486966', '64785', '488899', '80968', '491020', '459212', '477534', '358912', '301761', '346405', '414324', '101120', '90326', '44977', '160318', '291109', '463321', '49394', '427735', '104902', '482313', '467557', '36914', '24293', '120331', '405928', '113034', '188316', '181091', '326397', '294752', '28500', '280743', '122546', '276297', '10006', '265340', '475559', '375216', '324611', '330964', '105772', '130601', '254135', '39914', '34510', '162779', '175069', '343368', '312871', '178438', '458666', '16135', '373996', '520410', '373812', '67617', '302476', '215705', '14895', '284767', '257181', '84587', '104934', '337991', '61420', '23552', '241779', '208270', '35615', '231378', '465465', '208382', '218503', '255261', '338522', '172477', '170179', '219324', '102172', '388206', '285688', '452150', '224817', '111712', '223204', '225997', '52588', '24616', '483594', '371798', '280309', '92781', '95633', '88775', '483174', '229306', '168025', '105889', '316075', '210428', '497537', '393898', '204483', '88462', '376541', '281522', '136378', '267386', '378913', '55222', '440998', '45502', '74082', '92964', '327382', '386436', '50719', '15345', '55918', '76491', '287813', '271426', '139317', '261747', '421543', '172692', '367603', '155104', '135639', '132704', '389577', '69250', '410949', '333880', '391593', '391362', '213943', '277843', '230876', '375749', '213657', '498203', '288603', '389420', '438091', '197474', '374036', '323697', '323737', '213662', '49061', '101447', '343192', '192179', '85227', '350141', '86378', '136038', '73452', '58976', '256914', '48452', '20843', '86701', '245778', '383180', '202923', '271321', '190643', '218947', '458584', '61753', '356603', '410256', '217959', '54984', '227511', '533923', '356614', '257376', '324172', '88410', '18078', '234216', '188692', '43410', '137398', '90947', '254761', '433392', '443686', '384875', '302367', '202719', '167637', '380398', '468127', '180004', '279773', '149098', '340761', '102177', '171080', '90423', '234369', '114670', '174570', '333216', '173200', '369125', '147372', '391244', '88642', '413301', '150444', '67676', '316763', '167202', '390444', '125438', '141506', '86712', '179328', '88667', '278787', '373788', '284640', '283845', '280369', '260027', '34398', '50423', '65459', '358565', '398858', '96177', '368300', '336202', '317876', '207112', '41223', '418170', '72585', '117548', '272064', '161739', '242491', '16692', '72480', '247936', '210213', '293168', '98761', '361100', '225213', '101967', '136291', '279520', '12141', '22104', '494369', '77903', '47237', '28558', '90248', '350901', '175785', '326251', '228914', '185321', '425601', '90005', '258100', '120742', '181477', '91407', '80067', '36349', '71450'], 3: ['67664', '118843', '147477', '367987', '216068', '375362', '367828', '286484', '27060', '121712', '53353', '291409', '160494', '505748', '137187', '111559', '23613', '317681', '223242', '504956', '63907', '246579', '366021', '354751', '460069', '373269', '189127', '240135', '4205', '243909', '202414', '117542', '39189', '314777', '316673', '477848', '256689', '197284', '279302', '245792', '464367', '188540', '125915', '85354', '88978', '264064', '160902', '5197', '227191', '147791', '411505', '79749', '334186', '374277', '355173', '230530', '275663', '272034', '89021', '61297', '260930', '326743', '209058', '154255', '66022', '277459', '288624', '356161', '424837', '174273', '174274', '380641', '7841', '467378', '69539', '176085', '476635', '471921', '187347', '285826', '304396', '480525', '158999', '209879', '484256', '87155', '92096', '174425', '199548', '417578', '326076', '173235', '109866', '425400', '316766', '397529', '273854', '429284', '405042', '256036', '48279', '2866', '247330', '117230', '24572', '156441', '140648', '5006', '61779', '7397', '286813', '195336', '514820', '89453', '228169', '35199', '109267', '347092', '374964', '369209', '184910', '349456', '12276', '142258', '420640', '175723', '391030', '253665', '211806', '128013', '62902', '37056', '420610', '105811', '134206', '360201', '175958', '219761', '375050', '10005', '102185', '79233', '40999', '102815', '36315', '241052', '171380', '304615', '376363', '239498', '384789', '255144', '188823', '109123', '249336', '36256', '445597', '27928', '248337', '57924', '396461', '245066', '184921', '101968', '9177', '114588', '182723', '66', '41090', '294082', '33847', '15601', '470641', '24970', '169574', '364945', '166022', '402871', '281101', '386195', '259627', '237000', '317938', '132359', '176027', '460892', '50307', '139049', '59614', '65204', '49602', '118248', '454111', '93449', '77702', '19529', '28365', '88938', '42750', '265432', '94269', '114168', '239613', '462875', '45008', '253526', '183133', '210321', '220537', '201591', '44289', '308163', '77413', '288410', '50676', '276622', '175364', '430486', '288565', '430334', '322729', '293134', '34557', '208675', '284296', '331627', '54269', '159961', '256026', '36754', '475008', '149217', '233189', '171391', '231995', '72895', '52665', '426504', '21618', '504766', '232770', '36744', '395838', '44935', '9520', '245728', '292945', '266082', '202021', '81937', '264214', '167917', '95453', '481894', '48463', '221387', '501188', '417004', '361978', '108471', '329624', '351829', '26732', '90567', '109718', '81360', '233314', '265442', '255511', '143616', '445132', '259382', '308140', '23

3.3 Получите список рецептов, в этапах выполнения которых есть информация о времени (часы или минуты). Для отбора подходящих рецептов обратите внимание на атрибуты соответствующих тэгов.

In [64]:
recipes_with_time = []

for recipe in data_xml.find_all("recipe"):
    for step in recipe.find_all("step"):
        
        if "has_minutes" in step.attrs or "has_hours" in step.attrs:
            recipes_with_time.append(recipe.find("id").text)
            break


print(recipes_with_time_info[:5])

['44123', '35173', '453467', '306168', '50662']

3.4 Загрузите данные из файла `recipes_sample.csv` (__ЛР2__) в таблицу `recipes`. Для строк, которые содержат пропуски в столбце `n_steps`, заполните этот столбец на основе файла  `steps_sample.xml`. Строки, в которых столбец `n_steps` заполнен, оставьте без изменений.

In [76]:
import numpy as np

recipes = pd.read_csv('recipes_sample.csv', sep=',')
for recipe in data.find_all('recipe'):
    id = int(recipe.find('id').text)
    if np.isnan(recipes[recipes['id'] == id]['n_steps'].values[0]):
        recipes.loc[recipes.id == id, 'n_steps'] = len(recipe.find_all('step'))
recipes

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,11.0,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,3.0,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,5.0,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,7.0,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...,...,...
29995,zurie s holey rustic olive and cheddar bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
29996,zwetschgenkuchen bavarian plum cake,386977,240,177443,2009-08-24,22.0,"this is a traditional fresh plum cake, thought...",11.0
29997,zwiebelkuchen southwest german onion cake,103312,75,161745,2004-11-03,10.0,this is a traditional late summer early fall s...,NaN
29998,zydeco soup,486161,60,227978,2012-08-29,7.0,this is a delicious soup that i originally fou...,NaN
29999,cookies by design cookies on a stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

3.5 Проверьте, содержит ли столбец `n_steps` пропуски. Если нет, то преобразуйте его к целочисленному типу и сохраните результаты в файл `recipes_sample_with_filled_nsteps.csv`

In [ ]:
import numpy as np
if recipes["n_steps"].isna().sum() == 0:
    recipes["n_steps"] = recipes["n_steps"].astype(np.int)
    recipes.to_csv("./data/recipes_sample_with_filled_nsteps.csv", index=False)